name = "ai-lesson-planner"
compatibility_date = "2024-03-24"

[build]
command = "pip install -r requirements.txt"

[site]
bucket = "./static"

[env.production]
name = "ai-lesson-planner-prod"
route = "/"
workers_dev = true

[env.staging]
name = "ai-lesson-planner-staging"
route = "/"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "ai_lesson_planner"
database_id = "ai-lesson-planner-db"

[triggers]
crons = []

[build.upload]
format = "service-worker"
main = "./functions/app.py"

[python]
# Python configuration for Cloudflare
requirements = [
    "flask",
    "openai",
    "stripe",
    "supabase",
]